AWSTemplateFormatVersion: '2010-09-09'
Description: Creates EC2 instance with creation policy. You should have an IAM role created prior with CloudFormationSignalPolicy attached to the role and get the name of the instnace profile name from this.

Parameters:
  InstanceType: 
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
    ConstraintDescription: Must be a valid EC2 Instance Type.
  VPCId:
    Type: AWS::EC2::VPC::Id
    Default: #Replace with your VPC ID
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Default: #Replace with your Subnet ID

Resources:
  MyEC2Instance:
   Type: 'AWS::EC2::Instance'
   Properties:
     InstanceType: !Ref InstanceType
     ImageId: #Replace with your AMI ID
     SubnetId: !Ref SubnetId
     IamInstanceProfile: "" #Give your instance profile name, aws iam list-instance-profiles-for-role --role-name <nameofyourrole>
     UserData:
       Fn::Base64: !Sub |
         #!/bin/bash
         /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource MyEC2Instance --region ${AWS::Region}
         
  PrivateWaitHandle:
      Type: AWS::CloudFormation::WaitConditionHandle
 
    PrivateWaitCondition:
      Type: AWS::CloudFormation::WaitCondition
      Properties:
        Handle: !Ref PrivateWaitHandle
        Timeout: '36000'
        Count: 1

Outputs:
  InstanceId: 
    Value: !Ref MyEC2Instance

